import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  Nav  from '@/app/ui/nav'
import '@/app/ui/global.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <div className="w-full flex-none">
        <Nav />
      </div>
      <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
        {children}
      </div>
    </html>
  );
}
